### ISSUE TITLE
使用报错，请问是key的原因吗？

### ISSUE THREAD

**Issue by CIA-ai** [knownsec/Kunyu#18]
![kunyu](https://user-images.githubusercontent.com/83755939/138379506-c68bd17b-ba52-4445-8586-6e9d669afdd3.png)
您好，请问这种情况是什么原因呢

**Comment by wikiZ** [comment]
不是，因为近期zoomeye证书那的问题，师傅可以pip install kunyu安装，即可以正常使用。
