### ISSUE TITLE
kunyu windows安装完毕没反应

### ISSUE THREAD

**Issue by 0day-lili** [knownsec/Kunyu#27]
kunyu windows安装完毕后 输入console没反应  'kunyu' 不是内部或外部命令，也不是可运行的程序

**Comment by wikiZ** [comment]
你怎么安装的。。

**Comment by 0day-lili** [comment]
按照发布的文档，先是下载安装包，然后找到kunyu目录，安装request.txt ,最后在kunyu console没反应

**Comment by wikiZ** [comment]
直接kunyu console，你得python3 setup.py install后才能用，

**Comment by 0day-lili** [comment]
好的，感谢，我试试

**Comment by wikiZ** [comment]
关闭下吧

**Comment by 0day-lili** [comment]
> 关闭下吧
