### ISSUE TITLE
缺少module ，可是pocsuite3之类的已经pip安装了

### ISSUE THREAD

**Issue by SlientLamb** [knownsec/Kunyu#54]
ModuleNotFoundError: No module named 'pocsuite3.modules.listener.reverse_tcp'

**Comment by wikiZ** [comment]
重新单独安装一下这个pocsuite3模块，pip install --upgrade pocsuite3

**Comment by SlientLamb** [comment]
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\Python\\lib\\site-packages\\pocsuite3\\modules\\listener\\reverse_tcp.py'
![image](https://user-images.githubusercontent.com/42546535/161363292-742e3446-f65b-4073-bd0d-094d29649fbf.png)

**Comment by wikiZ** [comment]
https://github.com/knownsec/pocsuite3/blob/master/pocsuite3/modules/listener/reverse_tcp.py 你手动放进去看看
