### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by hututu2** [knownsec/Kunyu#57]
进行SearchHost时出现请求超时：
HTTPSConnectionPool(host='api.zoomeye.org', port=443): Read timed out. (read timeout=30)

注：查询过zoomeye用户余额是够的

**Comment by wikiZ** [comment]
请求超时了，可以set timeout = 50调大超时时间解决。

**Comment by wikiZ** [comment]
现在应该是好的，麻烦关一下issue吧。

**Comment by hututu2** [comment]
可以了可以了，谢谢
